# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5176c5474a55c473ddfa756f7a979f1456f0055c82b5697031f5dcdf4a94518ce9e65d03e81d0ed1d5f601f75d77a5a9f767cec4cbca8d785008d3570083866

test:
  secret_key_base: 5928e4a720b2821810e264fc6687e800d66e74fffe6cb38c983fe3f9381a7714ed3c1482323adbd5e6bb8e700c7d2fbdfe0939a998a067a6532d21fa5c575f2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
